# Generated by Django 4.0.2 on 2022-02-24 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 24, 15, 13, 17, 540072))),
                ('description', models.TextField(default=1)),
                ('bgimg', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
